version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    working_dir: /var/www/projeto-vox
    volumes:
      - .:/var/www/projeto-vox
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: symfony_db
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    image: nginx:alpine
    container_name: symfony_web
    ports:
      - "80:80"
    volumes:
      - ./symfony.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/projeto-vox
    depends_on:
      - app

volumes:
  pgdata:
