version: '3.8'

services:
  app:
    build:
      context: ./backend
    container_name: symfony_app
    volumes:
      - ./backend:/var/www/projeto-vox/backend
    ports:
      - "8000:80"
    environment:
      - APP_ENV=dev
      - DATABASE_URL=pgsql://user:password@db:5432/dbname
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
