version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    working_dir: /var/www/projeto-vox/backend
    volumes:
      - .:/var/www/projeto-vox:delegated
    depends_on:
      - db
    networks:
      - symfony_network
    environment:
      SYMFONY_DEV: 1
    command: php-fpm

  db:
    image: postgres:13
    container_name: symfony_db
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - symfony_network

  web:
    image: nginx:alpine
    container_name: symfony_web
    ports:
      - "80:80"
    volumes:
      - ./symfony.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/projeto-vox:delegated
    depends_on:
      - app
    networks:
      - symfony_network

volumes:
  pgdata:

networks:
  symfony_network:
    driver: bridge
